# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ded198766125339ce836575ee8593a78"
name = "AeroChat WhatsApp 1"
application_url = "https://shopifyapp-one.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_themes,write_themes"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [ "https://shopifyapp-one.vercel.app/api/auth" ]
